### PR TITLE
add support amg88xx

### PR DESCRIPTION
**Pull request by lowlevel-1989**
- driver for amg88xx
- module for amg88xx
- enable/disable from menuconfig the driver and module

# EXAMPLE

```
import lcd

from board import board_info
from fpioa_manager import fm
from modules import amg88xx

fm.fpioa.set_function(board_info.GROVE1, fm.fpioa.I2C0_SCLK)
fm.fpioa.set_function(board_info.GROVE2, fm.fpioa.I2C0_SDA)

lcd.init()

dev = amg88xx(0)

while 1:
    time.sleep(1/10)

    # GET DATA
    temperature = dev.temperature()
    mn, mx, _, _ = dev.min_max()

    #                    min,   max,   scale,  method
    img   = dev.to_image(mn,    mx,    30,     dev.METHOD_NEAREST)
    # img = dev.to_image(mn,    mx,    30,     dev.METHOD_BILINEAR)

    lcd.display(img.to_rainbow(1))
```

### CODE REVIEW

**Comment by junhuanchen** [comment]
Wow, it looks good, would it be better to use this driver written in C? Is it related to real-time performance?

**Comment by lowlevel-1989** [comment]
> Wow, it looks good, would it be better to use this driver written in C? Is it related to real-time performance?

if it is written in c, and it has very good performance.

**Comment by junhuanchen** [comment]
If there are modules with performance or timing requirements, you really have to use C to complete, such as ultrasound-related modules.

I haven't used this module yet, so I don't know how it works.

**Comment by lowlevel-1989** [comment]
METHOD_NEAREST 

https://www.youtube.com/watch?v=WInA-sDnGD8

**Comment by junhuanchen** [comment]
Thanks, got it! I can merge after I confirm.

**Comment by junhuanchen** [comment]
For this I am going to buy this module.

**Comment by lowlevel-1989** [comment]
no problem

**Pull request merged**
