### PR TITLE
board_info for cube

### PR DESCRIPTION
**Pull request by lowlevel-1989**
- Add pin Mapping
- Add pin Name

### CODE REVIEW

**Comment by junhuanchen** [comment]
Thank you so much, are you using this too? 
https://github.com/sipeed/MaixPy_scripts/tree/master/board

**Comment by lowlevel-1989** [comment]
> Thank you so much, are you using this too?
> https://github.com/sipeed/MaixPy_scripts/tree/master/board

yes I have used https://github.com/sipeed/MaixPy_scripts/tree/master/board, but adapt this to the new way of using the board_info system by adding for the cube both its buttons, the grove, spmod and led rgb pins

**Comment by junhuanchen** [comment]
Well done! I need some time to think before doing the merge~

**Comment by lowlevel-1989** [comment]
> Well done! I need some time to think before doing the merge~

no problem

**Review by junhuanchen — COMMENTED** [review]
pin_name & d & JTAG_TCK Is it necessary?

**Pull request merged**
